### ISSUE TITLE
Module installation creates rogue leftover files in home dir

### ISSUE THREAD

**Issue by zoffixznet** [jaffa4/inistorage#3]
I was toasting the ecosystem and found a stray `storage_test333` file left over in my home.

It's a bit rude to leave files lying around like that. You can create one using `$*TMPDIR.child('storage_test333')` or use [`Temp::Path` module](https://modules.perl6.org/repo/Temp::Path) that'll also ensure the filename is not already taken.

```
cpan@toaster:~$ cat storage_test333
[g]
no=7
text=d\\\x0anext\x0a
[record]
a0=3
a1=1
a2=4
a3=8
a4=3
```

**Comment by jaffa4** [comment]
I fixed...it but it seems unlink does not work always.
